export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_PRODUCT_INCART = 'DELETE_PRODUCT_INCART';
export const UPDATE_PRODUCT_INCART = 'UPDATE_PRODUCT_INCART';
export const CHANGE_MESSAGE = 'CHANGE_MESSAGE';